### ISSUE TITLE
Incompatible with HtmlWebpackPlugin 4.x

### ISSUE THREAD

**Issue by BluePsyduck** [andreashuber69/async-css-plugin#12]
The latest version of the AsyncCssPlugin is not compatible with 4.x releases of the HtmlWebpackPlugin.

Using a 4.x release (4.3 at the writing of this issue) will result in the following error:
```
AsyncCssPlugin[error]: htmlWebpackPluginAlterAssetTags is undefined. Is your configuration missing the HtmlWebpackPlugin?
```

This is because HtmlWebpackPlugin had a refactoring with version 4.0 and changed something with the hooks (see [changelog](https://github.com/jantimon/html-webpack-plugin/blob/master/CHANGELOG.md#breaking-changes)).

Is it possible to make this plugin compatible with HtmlWebpackPlugin 4.x?

**Comment by andreashuber69** [comment]
I will look into it, thanks for the report.

**Comment by andreashuber69** [comment]
> Is it possible to make this plugin compatible with HtmlWebpackPlugin 4.x?

It appears that the interface changes between 3.2 and 4.3  are such that it is not trivial to make a single version of AsyncCssPlugin compatible with both versions. I guess the simplest approach is publishing a new major version of this plugin which is compatible with 4.x, while maintaining compatibility with 3.2 with the 1.x version. I will not get to it before the weekend and given my limited understanding of the new interface it might take a while before it's done. PRs are always welcome!

**Comment by BluePsyduck** [comment]
Thank you for looking into it so quickly :)

Sadly I have no knowledge about webpack plugins, or TypeScript, at all, so I cannot really help you with this. But I will still try :D

I saw [another plugin](https://github.com/jamesjieye/html-webpack-exclude-assets-plugin) which had the same issue of [breaking with HtmlWebpackPlugin 4.x](https://github.com/jamesjieye/html-webpack-exclude-assets-plugin/issues/18). Someone [came up](https://github.com/jamesjieye/html-webpack-exclude-assets-plugin/issues/18#issuecomment-613569701) with a workaround (in JS), and some comments below an alternative version of the plugin was published which seems to handle both HtmlWebpackPlugin 3.x and 4.x in TypeScript: https://github.com/swimmadude66/html-webpack-skip-assets-plugin/blob/develop/src/plugin.ts#L29 Maybe this helps solving the issue in your plugin?

**Comment by andreashuber69** [comment]
> ... handle both HtmlWebpackPlugin 3.x and 4.x in TypeScript: https://github.com/swimmadude66/html-webpack-skip-assets-plugin/blob/develop/src/plugin.ts#L29 Maybe this helps solving the issue in your plugin?

Thanks, that's certainly a promising way to solve the problem, I'll try it this way first.

**Comment by andreashuber69** [comment]
> Maybe this helps solving the issue in your plugin?

I've published a new version. I've verified that it still works with v3. I have not yet had the time to test it with html-webpack-plugin v4. If you're in a hurry, you might want to give it a try. Otherwise I'll test that next week.

BTW, it's not perfect yet, as the package now reports a hard dependency to html-webpack-plugin 4.3, but that should not be a problem for your scenario. I will remove that later.

**Comment by BluePsyduck** [comment]
Thank you for your update :)

I am not in a hurry. But I tested it nonetheless :D 

While Webpack is no longer failing to build the project, your plugin now reports `AsyncCssPlugin_AsyncCssPlugin[error]: Cannot find hook. Is your configuration missing the HtmlWebpackPlugin?`, i.e. it fails to correctly recognize the HtmlWebpackPlugin v4.

I tried to look a lttile deeper into it (without any knowledge of TS :D), and one thing I found was that the line `if(HtmlWebpackPlugin && HtmlWebpackPlugin.getHooks)` is nowhere to be found in the compiled JS file. Instead the compiler seems to modify the class name, which results in a false condition when using the plugin.

**Comment by andreashuber69** [comment]
> I tried to look a lttile deeper into it (without any knowledge of TS :D), and one thing I found was that the line `if(HtmlWebpackPlugin && HtmlWebpackPlugin.getHooks)` is nowhere to be found in the compiled JS file. Instead the compiler seems to modify the class name, which results in a false condition when using the plugin.

True, I'm getting `html_webpack_plugin_AsyncCssPlugin.getHooks` as the name in the condition. `getHooks` is `undefined`, which is why you're seeing the error. Frankly, I'm not sure what is going on here, never mind how this is supposed to work at all.

I will dig deeper tomorrow and compare my compilation settings with the ones of the linked project.

**Comment by andreashuber69** [comment]
I've published another attempt at fixing this. It looks promising inasmuch as that it now appears to successfully get the hooks for html-webpack-plugin v4. However, when I enable `AsyncCssPlugin` in your project, the callback passed to `hooks.alterAssetTags.tap` never seems to be called.

This is strange, because the callback passed by `HtmlWebpackSkipAssetsPlugin` seems to be called at least once. Do you have an idea why this would happen in your project?

(I have limited direct experience with webpack, which is why I'm a bit hesitant to setup a fresh project to test the plugin)

**Comment by BluePsyduck** [comment]
I updated the plugin and it is now working fine: The stylesheet gets transformed to media=print etc., and when I dump through your plugin the checkHook() method is executed with the correct case. So for me everything is working as expected ;)

As the problem has been resolved, I am closing this issue. Thank you for your work :)

**Comment by andreashuber69** [comment]
> As the problem has been resolved, I am closing this issue. Thank you for your work :)

Great, thanks for testing!
